apiVersion: v1
kind: Service
metadata:
  name: rest-grpc-client
  labels:
    app: rest-grpc-client
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: rest-grpc-client 