version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "6565:6565"
    environment:
      SPRING_CLOUD_GCP_SPANNER_EMULATOR_HOST: "spanner:9010"
      SPRING_CLOUD_GCP_SPANNER_PROJECT_ID: "test-project"
      SPRING_CLOUD_GCP_SPANNER_INSTANCE_ID: "test-instance"
      SPRING_CLOUD_GCP_SPANNER_DATABASE: "test-db"
      CAMEL_COMPONENT_KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - spanner
      - kafka
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "9010:9010"
    command: ["/emulator"]
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
