apiVersion: batch/v1
kind: Job
metadata:
  name: k6-test-100tps-rest
  namespace: default
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: k6-test
        image: grafana/k6:0.47.0
        command: ["k6", "run", "/scripts/k6-rest-100tps.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-high-load-scripts
      restartPolicy: Never
  backoffLimit: 0 