apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-grpc-camel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-grpc-camel
  template:
    metadata:
      labels:
        app: rest-grpc-camel
    spec:
      containers:
      - name: rest-grpc-camel
        image: REGION-docker.pkg.dev/PROJECT_ID/my-repo/rest-grpc-camel-service:latest
        ports:
        - containerPort: 8080
        - containerPort: 6565
        env:
        - name: SPRING_CLOUD_GCP_SPANNER_INSTANCE_ID
          value: "YOUR_INSTANCE"
        - name: SPRING_CLOUD_GCP_SPANNER_DATABASE
          value: "YOUR_DB"
        - name: SPRING_CLOUD_GCP_SPANNER_PROJECT_ID
          value: "YOUR_PROJECT"
        - name: SPRING_CLOUD_GCP_SPANNER_CREDENTIALS_LOCATION
          value: "/etc/gcp/credentials.json"
        - name: CAMEL_COMPONENT_KAFKA_BROKERS
          value: "YOUR_KAFKA_BROKER:9092"
        volumeMounts:
        - name: gcp-creds
          mountPath: /etc/gcp
          readOnly: true
      volumes:
      - name: gcp-creds
        secret:
          secretName: gcp-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: rest-grpc-camel
spec:
  type: LoadBalancer
  selector:
    app: rest-grpc-camel
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 6565
    targetPort: 6565
    name: grpc
