apiVersion: batch/v1
kind: Job
metadata:
  name: k6-grpc-sample-test
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6"]
        args: ["run", "/scripts/k6-grpc-20tps.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        workingDir: /scripts
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-comprehensive-scripts 