apiVersion: batch/v1
kind: Job
metadata:
  name: k6-rest-20tps-test
  namespace: default
  labels:
    test-type: rest
    tps: "20"
spec:
  template:
    metadata:
      labels:
        test-type: rest
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        imagePullPolicy: Always
        command: ["k6"]
        args: ["run", "--out", "json=/tmp/results.json", "/scripts/k6-rest-20tps.js"]
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: K6_NO_CONNECTION_REUSE
          value: "false"
        - name: K6_NO_VU_CONNECTION_REUSE
          value: "false"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
  backoffLimit: 1
  activeDeadlineSeconds: 300
