apiVersion: batch/v1
kind: Job
metadata:
  name: k6-rest-steady-loadtest
spec:
  template:
    spec:
      containers:
      - name: k6
        image: australia-southeast2-docker.pkg.dev/silent-oxide-210505/rest-grpc-repo/k6-loadtest:latest
        imagePullPolicy: Always
        command: ["k6", "run", "k6-rest-steady.js"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
      restartPolicy: Never
  backoffLimit: 1 